<a href="https://colab.research.google.com/github/kavyasreemaniga/DATA_690/blob/main/Assignment%206/assignment_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment 06
### Note:
- For visualization, you should use Matplotlib, seaborn, or Plotly Express 
- Use this notebook as your template and follow the instructions

The first half of this assignment is similar to assignment 04.

This gives you a chance to refresh.

The second half is new and gives you a chance to perform additional practices.

You also get a chance to use some of the Python libraries and techniques.

The links to the zip file is:

- https://collegescorecard.ed.gov/data (This web page contains the link to the zip file)

- https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip (The link to the zip file)

You can run `!wget` command in Colab notebook to retrieve it directly, then run `!unzip` command to extract files (I have provided the cells to do so next for your convenience)

Your folder structure should look like this in your Colab enviroment:

- ...
- 'MERGED1996_97_PP.csv',
- 'MERGED2015_16_PP.csv',
- ...
- 'MERGED2017_18_PP.csv'
- ...

**Note: you should refresh the folder to see all files.**

## Step 1 - Retrieve the zip file

In [1]:
!wget https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip

--2022-10-10 03:46:47--  https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip
Resolving ed-public-download.app.cloud.gov (ed-public-download.app.cloud.gov)... 3.30.49.38, 3.30.138.208, 2600:1f12:18a:7d00:35c5:2f94:bca6:6240, ...
Connecting to ed-public-download.app.cloud.gov (ed-public-download.app.cloud.gov)|3.30.49.38|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 410294884 (391M) [application/zip]
Saving to: ‘CollegeScorecard_Raw_Data_09012022.zip’

CollegeScorecard_Ra  11%[=>                  ]  43.92M  13.8MB/s    in 3.2s

2022-10-10 03:46:51 (13.8 MB/s) - Connection closed at byte 46054996. Retrying.

--2022-10-10 03:46:52--  (try: 2)  https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip
Connecting to ed-public-download.app.cloud.gov (ed-public-download.app.cloud.gov)|3.30.49.38|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 410294884 (391M), 364239888 (347M) remaining [application/zip]
Saving to: ‘CollegeScorecard_Raw_Data_09012022.zip’

CollegeScorecard_Ra 100%[++=================>] 391.29M  20.3MB/s    in 18s

2022-10-10 03:47:11 (19.0 MB/s) - ‘CollegeScorecard_Raw_Data_09012022.zip’ saved [410294884/410294884]

## Step 2 - Unzip the zip file

In [2]:
!unzip CollegeScorecard_Raw_Data_09012022.zip

Archive:  CollegeScorecard_Raw_Data_09012022.zip
 extracting: Crosswalks.zip
  inflating: data.yaml
  inflating: FieldOfStudyData1415_1516_PP.csv
  inflating: FieldOfStudyData1516_1617_PP.csv
  inflating: FieldOfStudyData1617_1718_PP.csv
  inflating: FieldOfStudyData1718_1819_PP.csv
  inflating: MERGED1996_97_PP.csv
  inflating: MERGED1997_98_PP.csv
  inflating: MERGED1998_99_PP.csv
  inflating: MERGED1999_00_PP.csv
  inflating: MERGED2000_01_PP.csv
  inflating: MERGED2001_02_PP.csv
  inflating: MERGED2002_03_PP.csv
  inflating: MERGED2003_04_PP.csv
  inflating: MERGED2004_05_PP.csv
  inflating: MERGED2005_06_PP.csv
  inflating: MERGED2006_07_PP.csv
  inflating: MERGED2007_08_PP.csv
  inflating: MERGED2008_09_PP.csv
  inflating: MERGED2009_10_PP.csv
  inflating: MERGED2010_11_PP.csv
  inflating: MERGED2011_12_PP.csv
  inflating: MERGED2012_13_PP.csv
  inflating: MERGED2013_14_PP.csv
  inflating: MERGED2014_15_PP.csv
  inflating: MERGED2015_16_PP.csv
  inflating: MERGED2016_17_PP.csv
  inflating: MERGED2017_18_PP.csv
  inflating: MERGED2018_19_PP.csv
  inflating: MERGED2019_20_PP.csv
  inflating: MERGED2020_21_PP.csv
  inflating: Most-Recent-Cohorts-Field-of-Study.csv
  inflating: Most-Recent-Cohorts-Institution.csv

## Step 3 - Import Libraries

In [3]:
#(Write code below)
import pandas as pd
import os

In [44]:
import glob

In [45]:
import plotly.express as px

In [46]:
 import numpy as np

In [4]:
# This is not a good practice. A lot of repetitions.
# Not recommended

df_2020 = pd.read_csv("/content/MERGED2020_21_PP.csv", usecols=['UNITID', 'INSTNM', 'TUITIONFEE_IN'])
df_2020["year"] = 2020
df_2019 = pd.read_csv("/content/MERGED2019_20_PP.csv", usecols=['UNITID', 'INSTNM', 'TUITIONFEE_IN'])
df_2019["year"] = 2019
#.... (more code)
# df_2020 = pd.read_csv("/content/MERGED2020_21_PP.csv")
# df_all = pd.concat([df_1996, df_1997, ...., df_2020])
df_all = pd.concat([df_2020, df_2019])

df_all.sample(10)

        UNITID                                   INSTNM  TUITIONFEE_IN  year
5955    492315                       Poway Adult School            NaN  2020
520     127273                 Iliff School of Theology            NaN  2020
3206    222576                         Amarillo College         2136.0  2019
6609  45316303  Strayer University-North Raleigh Campus        13515.0  2019
2122    191083                   Erie Community College         5722.0  2020
1023    150677   Grace College and Theological Seminary        27432.0  2020
3201    222053        Volunteer State Community College         4332.0  2019
3797    246789         Unification Theological Seminary            NaN  2019
2420    199306                      Pfeiffer University        31060.0  2019
15      101189                      Faulkner University        22990.0  2020

## Step 4 - Display the current working directory using os.getcwd()

You would need to import a standard Python library called os which stands for operating system. so place that import statement in the previous cell. Since your notebook and your data files may or may not in the same folder, you want to make sure what the current working folder is and how to access a data file in a different folder.

In [5]:
#(Write code below)
os.getcwd()

'/content'

## Step 5 - Get the list of file names

os library has a method call listdir which generates a list of files in a directory/folder. Use this method to assign the contents (list of file names) of the data folder to a variable and display it. If necessary, you can use ../ construct to traverse to the parent folder and then to another foloder parallel to the current folder

In [6]:
#(Write code below)
name_list = os.listdir()
name_list

['.config',
 'MERGED2006_07_PP.csv',
 'MERGED2009_10_PP.csv',
 'MERGED2003_04_PP.csv',
 'MERGED1998_99_PP.csv',
 'Crosswalks.zip',
 'MERGED2012_13_PP.csv',
 'MERGED2019_20_PP.csv',
 'MERGED2011_12_PP.csv',
 'MERGED2014_15_PP.csv',
 'Most-Recent-Cohorts-Field-of-Study.csv',
 'MERGED2000_01_PP.csv',
 'MERGED2007_08_PP.csv',
 'MERGED2016_17_PP.csv',
 'FieldOfStudyData1718_1819_PP.csv',
 'MERGED2018_19_PP.csv',
 'MERGED2008_09_PP.csv',
 'MERGED2002_03_PP.csv',
 'MERGED2004_05_PP.csv',
 'MERGED2010_11_PP.csv',
 'MERGED2013_14_PP.csv',
 'MERGED2005_06_PP.csv',
 'FieldOfStudyData1516_1617_PP.csv',
 'MERGED1999_00_PP.csv',
 'MERGED2015_16_PP.csv',
 'MERGED1996_97_PP.csv',
 'FieldOfStudyData1415_1516_PP.csv',
 'FieldOfStudyData1617_1718_PP.csv',
 'MERGED2017_18_PP.csv',
 'data.yaml',
 'Most-Recent-Cohorts-Institution.csv',
 'MERGED1997_98_PP.csv',
 'MERGED2020_21_PP.csv',
 'CollegeScorecard_Raw_Data_09012022.zip',
 'MERGED2001_02_PP.csv',
 'sample_data']

## Step 6 - Process only the yearly data files

The folder contains files that are not the yearly data files. Write code to remove the unwanted files from the list variable.

Note: don't remove/delete these files from the folder in the folder.
For example, use the file extension to only use the csv files or use the name patter - data file name begins with "MERGED". You can use the concept of list comprehension to write just *one* line of code as well as using a for loop, your choice.

In [11]:
yearly_list = [file_name for file_name in name_list if file_name.startswith("MERGED")]

yearly_list

['MERGED2006_07_PP.csv',
 'MERGED2009_10_PP.csv',
 'MERGED2003_04_PP.csv',
 'MERGED1998_99_PP.csv',
 'MERGED2012_13_PP.csv',
 'MERGED2019_20_PP.csv',
 'MERGED2011_12_PP.csv',
 'MERGED2014_15_PP.csv',
 'MERGED2000_01_PP.csv',
 'MERGED2007_08_PP.csv',
 'MERGED2016_17_PP.csv',
 'MERGED2018_19_PP.csv',
 'MERGED2008_09_PP.csv',
 'MERGED2002_03_PP.csv',
 'MERGED2004_05_PP.csv',
 'MERGED2010_11_PP.csv',
 'MERGED2013_14_PP.csv',
 'MERGED2005_06_PP.csv',
 'MERGED1999_00_PP.csv',
 'MERGED2015_16_PP.csv',
 'MERGED1996_97_PP.csv',
 'MERGED2017_18_PP.csv',
 'MERGED1997_98_PP.csv',
 'MERGED2020_21_PP.csv',
 'MERGED2001_02_PP.csv']

## Step 7 - Load data files
 
Now that you have a clean list of the yearly files, you want to loop through them and read them into a dataframe one at a time. You only load six columns: ["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"].

You should use "usecols" option of Pandas to avoid reading unwanted columns. You also want to add a new column call "YEAR" to differentiate the data frames from each other. The YEAR variable should be yyyy format so tht you can convert them into integer. If you use the format yyyy-yy (such as 1997-98 school year), you will not be able to convert them directly to integer. If you use scatter plot, the YEAR needs to be converted to integer or float. 

You would use an empty list and append the yearly dataframes to the list. After all data files are loaded and appended to the list, you would use Pandas to concatenate them into a new single data frame.

Note: this exercise incorporates many techques we learned before:

- list (creating an empty, append an item to the list)
- for loop 
- read only the needed columns from a file (using usecols option)
- add a new column to a data frame
- concatenate multiple dataframes into a single one

This exercise may appear challenging but it worths the effort. You will learn a lot and love it. I promise.

In [13]:
k = "MERGED2020_21_PP.csv"

k[6:10]

'2020'

In [26]:
#(Write code here)

# df_all = pd.DataFrame()  this empty dataframe does not work for the append method.

yearly_list.sort()

print("processing file", yearly_list[0])
df_all = pd.read_csv("/content/" + yearly_list[0], usecols=["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"])
df_all["year"] = yearly_list[0][6:10]
print(df_all.shape)

for yearly_file in yearly_list[1:]:
    print("processing file", yearly_file)
    df = pd.read_csv("/content/" + yearly_file, usecols=["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"])
    df["year"] = yearly_file[6:10]
    df_all = df_all.append(df, ignore_index = True)
    print(df_all.shape)

processing file MERGED1996_97_PP.csv
(7007, 7)
processing file MERGED1997_98_PP.csv
(13941, 7)
processing file MERGED1998_99_PP.csv
(20643, 7)
processing file MERGED1999_00_PP.csv
(27252, 7)
processing file MERGED2000_01_PP.csv
(33906, 7)
processing file MERGED2001_02_PP.csv
(40631, 7)
processing file MERGED2002_03_PP.csv
(47283, 7)
processing file MERGED2003_04_PP.csv
(53956, 7)
processing file MERGED2004_05_PP.csv
(60703, 7)
processing file MERGED2005_06_PP.csv
(67602, 7)
processing file MERGED2006_07_PP.csv
(74553, 7)
processing file MERGED2007_08_PP.csv
(81524, 7)
processing file MERGED2008_09_PP.csv
(88579, 7)
processing file MERGED2009_10_PP.csv
(95796, 7)
processing file MERGED2010_11_PP.csv
(103266, 7)
processing file MERGED2011_12_PP.csv
(111012, 7)
processing file MERGED2012_13_PP.csv
(118874, 7)
processing file MERGED2013_14_PP.csv
(126743, 7)
processing file MERGED2014_15_PP.csv
(134509, 7)
processing file MERGED2015_16_PP.csv
(142175, 7)
processing file MERGED2016_17_PP.csv
(149413, 7)
processing file MERGED2017_18_PP.csv
(156525, 7)
processing file MERGED2018_19_PP.csv
(163332, 7)
processing file MERGED2019_20_PP.csv
(170026, 7)
processing file MERGED2020_21_PP.csv
(176707, 7)

In [27]:
df_all.sample(10)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
40520,439330,DeVry University-Maryland,MD,2.0,NaN,NaN,2001
65475,248527,Cloyd's Beauty School 3 Inc,LA,5.0,NaN,NaN,2005
87561,442684,Stenotype Institute of Jacksonville Inc-Orlando,FL,5.0,NaN,NaN,2008
143327,151962,Mid-America College of Funeral Service,IN,3.0,NaN,11150.0,2016
106859,217059,York College of Pennsylvania,PA,2.0,0.7266,15880.0,2011
53778,441894,South Branch Career and Technical Center,WV,5.0,NaN,NaN,2003
114678,219639,Baptist Health Sciences University,TN,5.0,0.2460,11830.0,2012
136278,170611,Michigan College of Beauty-Monroe,MI,3.0,NaN,NaN,2015
147816,455008,Tricoci University of Beauty Culture-Rockford,IL,3.0,NaN,NaN,2016
168369,455734,California Nurses Educational Institute,CA,8.0,NaN,NaN,2019

## Step 8 - Explore the new dataframe 

For example, # of observations, varibles, head, tail, sample, missing values, statistics, etc.

In [28]:
#(Write code here)
len(df_all)

176707

In [29]:
df_all.shape

(176707, 7)

In [30]:
df_all.head()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
0,100636,Community College of the Air Force,AL,0.0,NaN,NaN,1996
1,100654,Alabama A & M University,AL,5.0,NaN,NaN,1996
2,100663,University of Alabama at Birmingham,AL,5.0,NaN,NaN,1996
3,100672,ALABAMA AVIATION AND TECHNICAL COLLEGE,AL,5.0,NaN,NaN,1996
4,100690,Amridge University,AL,5.0,NaN,NaN,1996

In [31]:
df_all.tail()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
176702,49576719,Pennsylvania State University-Penn State Wilke...,PA,2.0,NaN,13604.0,2020
176703,49576720,Pennsylvania State University-Penn State York,PA,2.0,NaN,14486.0,2020
176704,49576721,Pennsylvania State University-Penn State Great...,PA,2.0,NaN,NaN,2020
176705,49576722,Pennsylvania State University-Penn State Harri...,PA,2.0,NaN,15216.0,2020
176706,49576723,Pennsylvania State University-Penn State Brand...,PA,2.0,NaN,14486.0,2020

In [32]:
df_all.sample(4)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
94533,442356,Pennsylvania College of Health Sciences,PA,2.0,0.3848,15650.0,2009
59535,416971,Carousel Beauty College-Springfield,OH,3.0,NaN,NaN,2004
90585,171881,Kuyper College,MI,3.0,0.4756,15218.0,2009
75478,138372,Orange Technical College-Westside Campus,FL,5.0,NaN,NaN,2007

In [33]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176707 entries, 0 to 176706
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   UNITID         176707 non-null  int64
 1   INSTNM         176707 non-null  object
 2   STABBR         176707 non-null  object
 3   REGION         176706 non-null  float64
 4   ADM_RATE       48863 non-null   float64
 5   TUITIONFEE_IN  86867 non-null   float64
 6   year           176707 non-null  object
dtypes: float64(3), int64(1), object(3)
memory usage: 9.4+ MB

## Step 9 - UMBC 

The dataframe contains many years of data of all U.S. colleges. let's just look at UMBC. Filter/query the dataframe to retrieve only rows that belong to UMBC (one row represent one year). Save the UMNC data to a new data frame. using a new variable for the UMBC data frame, so that the old big data frame is still available for later use.

In [34]:
#(Write code here)
DF_1=df_all.loc[df_all['INSTNM'] == "University of Maryland-Baltimore County"]  # searching for umbc
DF_1

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996
9056,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997
15923,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998
22598,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000
35821,163268,University of Maryland-Baltimore County,MD,2.0,0.6551,5910.0,2001
42524,163268,University of Maryland-Baltimore County,MD,2.0,0.6327,6362.0,2002
49156,163268,University of Maryland-Baltimore County,MD,2.0,0.5757,7388.0,2003
55786,163268,University of Maryland-Baltimore County,MD,2.0,0.7014,8020.0,2004
62522,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005
69401,163268,University of Maryland-Baltimore County,MD,2.0,0.7153,8622.0,2006
76332,163268,University of Maryland-Baltimore County,MD,2.0,0.6895,8708.0,2007
83291,163268,University of Maryland-Baltimore County,MD,2.0,0.7174,8780.0,2008
90324,163268,University of Maryland-Baltimore County,MD,2.0,0.6890,8872.0,2009
97506,163268,University of Maryland-Baltimore County,MD,2.0,0.6589,9171.0,2010
104960,163268,University of Maryland-Baltimore County,MD,2.0,0.6081,9467.0,2011
112672,163268,University of Maryland-Baltimore County,MD,2.0,0.6035,9764.0,2012
120503,163268,University of Maryland-Baltimore County,MD,2.0,0.6315,10068.0,2013
128353,163268,University of Maryland-Baltimore County,MD,2.0,0.5961,10384.0,2014
136064,163268,University of Maryland-Baltimore County,MD,2.0,0.5942,11006.0,2015
143685,163268,University of Maryland-Baltimore County,MD,2.0,0.5683,11264.0,2016
150891,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017
157940,163268,University of Maryland-Baltimore County,MD,2.0,0.5794,11778.0,2018
164723,163268,University of Maryland-Baltimore County,MD,2.0,0.6103,12028.0,2019
171401,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020

## Step 10 - Explore the new dataframe

For example, # of observations, varibles, head, tail, sample, missing values, statistics, etc

In [36]:
#(Write code here)
DF_1.shape

(25, 7)

## Step 11 - Plot UMBC's in-state tuition overtime Bar Chart

In [37]:
#(Write code here)
DF_1.head()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996
9056,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997
15923,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998
22598,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000

In [38]:
DF_1.tail()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
143685,163268,University of Maryland-Baltimore County,MD,2.0,0.5683,11264.0,2016
150891,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017
157940,163268,University of Maryland-Baltimore County,MD,2.0,0.5794,11778.0,2018
164723,163268,University of Maryland-Baltimore County,MD,2.0,0.6103,12028.0,2019
171401,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020

In [39]:
DF_1.sample(7)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
120503,163268,University of Maryland-Baltimore County,MD,2.0,0.6315,10068.0,2013
150891,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017
76332,163268,University of Maryland-Baltimore County,MD,2.0,0.6895,8708.0,2007
35821,163268,University of Maryland-Baltimore County,MD,2.0,0.6551,5910.0,2001
83291,163268,University of Maryland-Baltimore County,MD,2.0,0.7174,8780.0,2008
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000
15923,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998

In [40]:
DF_1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25 entries, 2151 to 171401
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   UNITID         25 non-null     int64
 1   INSTNM         25 non-null     object
 2   STABBR         25 non-null     object
 3   REGION         25 non-null     float64
 4   ADM_RATE       20 non-null     float64
 5   TUITIONFEE_IN  21 non-null     float64
 6   year           25 non-null     object
dtypes: float64(3), int64(1), object(3)
memory usage: 1.6+ KB

In [41]:
DF_1.isnull()

        UNITID  INSTNM  STABBR  REGION  ADM_RATE  TUITIONFEE_IN   year
2151     False   False   False   False      True           True  False
9056     False   False   False   False      True           True  False
15923    False   False   False   False      True           True  False
22598    False   False   False   False      True           True  False
29178    False   False   False   False      True          False  False
35821    False   False   False   False     False          False  False
42524    False   False   False   False     False          False  False
49156    False   False   False   False     False          False  False
55786    False   False   False   False     False          False  False
62522    False   False   False   False     False          False  False
69401    False   False   False   False     False          False  False
76332    False   False   False   False     False          False  False
83291    False   False   False   False     False          False  False
90324    False   False   False   False     False          False  False
97506    False   False   False   False     False          False  False
104960   False   False   False   False     False          False  False
112672   False   False   False   False     False          False  False
120503   False   False   False   False     False          False  False
128353   False   False   False   False     False          False  False
136064   False   False   False   False     False          False  False
143685   False   False   False   False     False          False  False
150891   False   False   False   False     False          False  False
157940   False   False   False   False     False          False  False
164723   False   False   False   False     False          False  False
171401   False   False   False   False     False          False  False

In [42]:
DF_1.describe()

         UNITID  REGION   ADM_RATE  TUITIONFEE_IN
count      25.0    25.0  20.000000      21.000000
mean   163268.0     2.0   0.641880    9168.571429
std         0.0     0.0   0.051853    1854.082079
min    163268.0     2.0   0.568300    5490.000000
25%    163268.0     2.0   0.600600    8520.000000
50%    163268.0     2.0   0.632100    9171.000000
75%    163268.0     2.0   0.690825   10384.000000
max    163268.0     2.0   0.717400   12028.000000

## Step 12 - Plot UMBC's in-state tuition overtime using line Chart

In [50]:
#(Write code here)
fig = px.line(DF_1, x="year", y="TUITIONFEE_IN", title='UMBC in-state tution overtime')
fig.show()

In [49]:
fig = px.bar(DF_1, x='year', y='TUITIONFEE_IN')
fig.show()

## Step 13 - Tuition Growth Rate

Now let's look at the tuition growth rate year over year. We need to calculate UMBC tuition change percentage each year. First convert the TUITIONFEE_IN column to a Python List

In [51]:
#(Write code here)
TUITIONFEE_IN_list = DF_1.TUITIONFEE_IN.tolist()
print(TUITIONFEE_IN_list)

[nan, nan, nan, nan, 5490.0, 5910.0, 6362.0, 7388.0, 8020.0, 8520.0, 8622.0, 8708.0, 8780.0, 8872.0, 9171.0, 9467.0, 9764.0, 10068.0, 10384.0, 11006.0, 11264.0, 11518.0, 11778.0, 12028.0, 9420.0]

In [52]:
len(TUITIONFEE_IN_list)

25

## Step 14 - Loop through the list and calculate the % change each year over the prior year

This takes some effort. Not hard, just some abstract/logical thinking and some experiments. Have fun on this one.

In [53]:
 #(Write code here)
 change = np.array(TUITIONFEE_IN_list, dtype=float)
per_change=np.diff(change) / change[:-1] * 100.
per_change

array([         nan,          nan,          nan,          nan,
         7.65027322,   7.64805415,  16.12700409,   8.55441256,
         6.23441397,   1.1971831 ,   0.99744839,   0.82682591,
         1.04783599,   3.37015329,   3.22756515,   3.13721348,
         3.11347808,   3.13865713,   5.98998459,   2.3441759 ,
         2.25497159,   2.25733634,   2.12260146, -21.68274027])

## Step 15 - Round up the percentage to two decimal points

The resulting number has many decimal points which are unnecessary and not visually appealing. You can use for loop. Or better, use list comprehension for simplicity/brevity.

In [54]:
#(Write code here)
roundup_list = [round(item, 2) for item in per_change]
print(roundup_list)

[nan, nan, nan, nan, 7.65, 7.65, 16.13, 8.55, 6.23, 1.2, 1.0, 0.83, 1.05, 3.37, 3.23, 3.14, 3.11, 3.14, 5.99, 2.34, 2.25, 2.26, 2.12, -21.68]

In [55]:
len(roundup_list)

24

In [56]:
roundup_list.append(0)
len(roundup_list)

25

## Step 16 - Add the list of the percentages to the dataframe as a new column ("PCT_CHANGE")

Not as hard as you may think. If you get stuck, you think too hard. Google it and you will find the answer.

In [57]:
#(Write code here)
DF_1["percent_change_tution"] = roundup_list

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [58]:
DF_1

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year,percent_change_tution
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996,NaN
9056,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997,NaN
15923,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998,NaN
22598,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999,NaN
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000,7.65
35821,163268,University of Maryland-Baltimore County,MD,2.0,0.6551,5910.0,2001,7.65
42524,163268,University of Maryland-Baltimore County,MD,2.0,0.6327,6362.0,2002,16.13
49156,163268,University of Maryland-Baltimore County,MD,2.0,0.5757,7388.0,2003,8.55
55786,163268,University of Maryland-Baltimore County,MD,2.0,0.7014,8020.0,2004,6.23
62522,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005,1.20
69401,163268,University of Maryland-Baltimore County,MD,2.0,0.7153,8622.0,2006,1.00
76332,163268,University of Maryland-Baltimore County,MD,2.0,0.6895,8708.0,2007,0.83
83291,163268,University of Maryland-Baltimore County,MD,2.0,0.7174,8780.0,2008,1.05
90324,163268,University of Maryland-Baltimore County,MD,2.0,0.6890,8872.0,2009,3.37
97506,163268,University of Maryland-Baltimore County,MD,2.0,0.6589,9171.0,2010,3.23
104960,163268,University of Maryland-Baltimore County,MD,2.0,0.6081,9467.0,2011,3.14
112672,163268,University of Maryland-Baltimore County,MD,2.0,0.6035,9764.0,2012,3.11
120503,163268,University of Maryland-Baltimore County,MD,2.0,0.6315,10068.0,2013,3.14
128353,163268,University of Maryland-Baltimore County,MD,2.0,0.5961,10384.0,2014,5.99
136064,163268,University of Maryland-Baltimore County,MD,2.0,0.5942,11006.0,2015,2.34
143685,163268,University of Maryland-Baltimore County,MD,2.0,0.5683,11264.0,2016,2.25
150891,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017,2.26
157940,163268,University of Maryland-Baltimore County,MD,2.0,0.5794,11778.0,2018,2.12
164723,163268,University of Maryland-Baltimore County,MD,2.0,0.6103,12028.0,2019,-21.68
171401,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020,0.00

## Step 17 - Finaly, we can make the plot tuition growth rate year over year - bar first, then line chart

In [60]:
# (write code here)

fig = px.bar(DF_1, x='year', y='percent_change_tution')
fig.show()

In [61]:
fig = px.line(DF_1, x="year", y="percent_change_tution", title='UMBC in-state percent_change_tution over year')
fig.show()

## Step 18 - Define Growth Rate Function

Since we want to do the same calculation for JHU. Instead of doing it piecemeal as we did for UMBC. Let's create a function which can be reused for any college. This function takes a list of tuitions and return a list of percentage changes year over year. This function can be used later.

In [62]:
#(Write code here)
def growth_rate(tutionlist):
   a = np.array(TUITIONFEE_IN_list, dtype=float)
   per_change=np.diff(a) / a[:-1] * 100.
   roundup_list = [round(item, 2) for item in per_change]
   roundup_list.append(0)
   return roundup_list

In [63]:
TUITIONFEE_IN_list = DF_1.TUITIONFEE_IN.tolist()

print(growth_rate(TUITIONFEE_IN_list))

[nan, nan, nan, nan, 7.65, 7.65, 16.13, 8.55, 6.23, 1.2, 1.0, 0.83, 1.05, 3.37, 3.23, 3.14, 3.11, 3.14, 5.99, 2.34, 2.25, 2.26, 2.12, -21.68, 0]

## Step 19 - Get JHU Data

The dataframe contains many years of data of all U.S. colleges. Let's just look at JHU. Filter/query the dataframe to retrieve only rows that belong to JHU. Save the JHU data to a new data frame using a new variable so that the old big data frame is still available for later use.

In [64]:
#(Write code here)
DF_2=df_all.loc[df_all['INSTNM'] == "Johns Hopkins University"]  
DF_2

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year
2139,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1996
9046,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1997
15914,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1998
22589,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1999
29169,162928,Johns Hopkins University,MD,2.0,NaN,24930.0,2000
35812,162928,Johns Hopkins University,MD,2.0,0.3431,26210.0,2001
42515,162928,Johns Hopkins University,MD,2.0,0.3506,27390.0,2002
49148,162928,Johns Hopkins University,MD,2.0,0.3060,28730.0,2003
55779,162928,Johns Hopkins University,MD,2.0,0.3071,30140.0,2004
62515,162928,Johns Hopkins University,MD,2.0,0.3509,31620.0,2005
69394,162928,Johns Hopkins University,MD,2.0,0.2792,33900.0,2006
76325,162928,Johns Hopkins University,MD,2.0,0.2571,35900.0,2007
83284,162928,Johns Hopkins University,MD,2.0,0.2609,37700.0,2008
90317,162928,Johns Hopkins University,MD,2.0,0.2782,39150.0,2009
97499,162928,Johns Hopkins University,MD,2.0,0.2225,40680.0,2010
104953,162928,Johns Hopkins University,MD,2.0,0.1940,42280.0,2011
112665,162928,Johns Hopkins University,MD,2.0,0.1843,43390.0,2012
120496,162928,Johns Hopkins University,MD,2.0,0.1813,45470.0,2013
128346,162928,Johns Hopkins University,MD,2.0,0.1608,47060.0,2014
136057,162928,Johns Hopkins University,MD,2.0,0.1412,48710.0,2015
143678,162928,Johns Hopkins University,MD,2.0,0.1284,50410.0,2016
150886,162928,Johns Hopkins University,MD,2.0,0.1254,52170.0,2017
157935,162928,Johns Hopkins University,MD,2.0,0.1148,53740.0,2018
164718,162928,Johns Hopkins University,MD,2.0,0.1117,55350.0,2019
171396,162928,Johns Hopkins University,MD,2.0,0.1106,54160.0,2020

## Step 20 - Plot JHU's in-state tuition overtime

Let's plot bar and then line chart.

In [65]:
# <14> 
# Plot JHU's in-state tuition overtime from 1996 to 2019. 
# Let's plot bar and line chart together

#(Write code here)
DF_3=DF_2.loc[DF_2['year'] != "2020"]  
DF_3
fig = px.bar(DF_3, x='year', y='TUITIONFEE_IN')
fig.show()

fig = px.line(DF_3, x="year", y="TUITIONFEE_IN", title='UMBC in-state tution overtime')
fig.show()

## Step 21 - Calculate Tuition Growth Rate using the Function defined earlier

In [66]:
# Write code here
TUITIONFEE_IN_list = DF_2.TUITIONFEE_IN.tolist()
print(TUITIONFEE_IN_list)
x=growth_rate(TUITIONFEE_IN_list)
print(x)

[nan, nan, nan, nan, 24930.0, 26210.0, 27390.0, 28730.0, 30140.0, 31620.0, 33900.0, 35900.0, 37700.0, 39150.0, 40680.0, 42280.0, 43390.0, 45470.0, 47060.0, 48710.0, 50410.0, 52170.0, 53740.0, 55350.0, 54160.0]
[nan, nan, nan, nan, 5.13, 4.5, 4.89, 4.91, 4.91, 7.21, 5.9, 5.01, 3.85, 3.91, 3.93, 2.63, 4.79, 3.5, 3.51, 3.49, 3.49, 3.01, 3.0, -2.15, 0]

## Step 22 - Add the list of percentage changes to the dataframe as a new column ("PCT_CHANGE")

In [68]:
#(Write code here)
DF_2["percent_change_tution"] = x
DF_2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,year,percent_change_tution
2139,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1996,NaN
9046,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1997,NaN
15914,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1998,NaN
22589,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1999,NaN
29169,162928,Johns Hopkins University,MD,2.0,NaN,24930.0,2000,5.13
35812,162928,Johns Hopkins University,MD,2.0,0.3431,26210.0,2001,4.50
42515,162928,Johns Hopkins University,MD,2.0,0.3506,27390.0,2002,4.89
49148,162928,Johns Hopkins University,MD,2.0,0.3060,28730.0,2003,4.91
55779,162928,Johns Hopkins University,MD,2.0,0.3071,30140.0,2004,4.91
62515,162928,Johns Hopkins University,MD,2.0,0.3509,31620.0,2005,7.21
69394,162928,Johns Hopkins University,MD,2.0,0.2792,33900.0,2006,5.90
76325,162928,Johns Hopkins University,MD,2.0,0.2571,35900.0,2007,5.01
83284,162928,Johns Hopkins University,MD,2.0,0.2609,37700.0,2008,3.85
90317,162928,Johns Hopkins University,MD,2.0,0.2782,39150.0,2009,3.91
97499,162928,Johns Hopkins University,MD,2.0,0.2225,40680.0,2010,3.93
104953,162928,Johns Hopkins University,MD,2.0,0.1940,42280.0,2011,2.63
112665,162928,Johns Hopkins University,MD,2.0,0.1843,43390.0,2012,4.79
120496,162928,Johns Hopkins University,MD,2.0,0.1813,45470.0,2013,3.50
128346,162928,Johns Hopkins University,MD,2.0,0.1608,47060.0,2014,3.51
136057,162928,Johns Hopkins University,MD,2.0,0.1412,48710.0,2015,3.49
143678,162928,Johns Hopkins University,MD,2.0,0.1284,50410.0,2016,3.49
150886,162928,Johns Hopkins University,MD,2.0,0.1254,52170.0,2017,3.01
157935,162928,Johns Hopkins University,MD,2.0,0.1148,53740.0,2018,3.00
164718,162928,Johns Hopkins University,MD,2.0,0.1117,55350.0,2019,-2.15
171396,162928,Johns Hopkins University,MD,2.0,0.1106,54160.0,2020,0.00

## Step 23 - Plot the JHU percentage changes tuitions over time

Bar plot first, then line plot.

In [69]:
#(Write code here)
fig = px.bar(DF_2, x='year', y='percent_change_tution')
fig.show()

fig = px.line(DF_2, x="year", y="percent_change_tution", title='jhu percentange change tution overtime')
fig.show()

## Step 24 - Compare UMBC and JHU 

In order to plot both UMBC and JHU tuition change over time in the same plot, we need to combine the two datasets using the common key of YEAR. 

First make a umbc2 dataframe with only two columns needed. We don't need other columns. Also change the column name from "PCT_CHANGE" to "UMBC_PCT" in preparation for the merge. This is because both umbc and jhu dataframe have the same column name "PCT_CHANGE", we rename them to there is no collision during the merge. BTW, Pandas handles collision gracefully, Feel free to try it without changing the column names.

In [70]:
#(Write code here)

umbc_2 = DF_1[['percent_change_tution', 'year']]
umbc_2.rename(columns = {'percent_change_tution': 'UMBC_PCT'}, inplace=True)
umbc_2.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       UMBC_PCT  year
2151        NaN  1996
9056        NaN  1997
15923       NaN  1998
22598       NaN  1999
29178      7.65  2000

## Step 25 

Then make a jhu2 dataframe with only two columns needed. WE don't need other columns. Also change the column name from "PCT_CHANGE" to "JHU_PCT"  in preparation for the merge

In [71]:
#(Write code here)

jhu2= DF_2[['percent_change_tution', 'year']]
jhu2.rename(columns = {'percent_change_tution': 'JHU_PCT'}, inplace=True)
jhu2.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

       JHU_PCT  year
2139       NaN  1996
9046       NaN  1997
15914      NaN  1998
22589      NaN  1999
29169     5.13  2000

## Step 26 - Merger the two data frames and display the new dataframe

In [72]:
#(Write code here)
DF_4=pd.merge(umbc_2, jhu2, left_on='year', right_on='year', how='inner')
DF_4

    UMBC_PCT  year  JHU_PCT
0        NaN  1996      NaN
1        NaN  1997      NaN
2        NaN  1998      NaN
3        NaN  1999      NaN
4       7.65  2000     5.13
5       7.65  2001     4.50
6      16.13  2002     4.89
7       8.55  2003     4.91
8       6.23  2004     4.91
9       1.20  2005     7.21
10      1.00  2006     5.90
11      0.83  2007     5.01
12      1.05  2008     3.85
13      3.37  2009     3.91
14      3.23  2010     3.93
15      3.14  2011     2.63
16      3.11  2012     4.79
17      3.14  2013     3.50
18      5.99  2014     3.51
19      2.34  2015     3.49
20      2.25  2016     3.49
21      2.26  2017     3.01
22      2.12  2018     3.00
23    -21.68  2019    -2.15
24      0.00  2020     0.00

## Step 27 - Plot UMBC and JHU separately on the same line plot

In [73]:
#(Write code here)
fig = px.line(DF_4, x='year', y=['JHU_PCT', 'UMBC_PCT'], title='comparision of jhu and umbc')
fig.show()

## Step 28 - Document your observation of the comparison plots using the following Markdown cell

#### Based on my observation of the plots
#### blah, blah 
#### blah, blah
#### ...
#### blah, blah

In [ ]:
# The end.

According to the plot, we can say that UMBC has higher tution rate from 2000 to 2002 compared to JHU, which has reached a peak of 15 percent in 2002. JHU and UMBC has maintained a steady percent change but UMBC has slightly lower change in tuition growth rate from 2005 to 2008. In 2019, both JHU and UMBC has reached its lowest percent growth rate change at -23 and -3 percent respectively. Overall, JHU has higher percent tution fee growth rate compared to UMBC.